name: CodeCov

on:
  pull_request:

jobs:

  build-test-publish-to-CodeCov:
    runs-on: ubuntu-latest

      permissions:
        contents: write
        
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 

      - name: Build package
        run: |
          python -m build 

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: backend
          flags: frontend